export const dadosReaisMaquinas = [
  {
    id: "1",
    tag: "SC-2020-02",
    modelo: "FX 18 Secadores e Filtros",
    numeroSerie: "CAI921341",
    localizacao: "Filtragem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Parada",
    manutencaoPreventiva: "OK",
    dataParada: "2025-09-26",
    acao: "ATLAS",
    observacoes: "Equipamento com vazamento de gás",
    responsavel: "ATLAS",
    tempo: 109,
  },
  {
    id: "2",
    tag: "CB-2316SA-07",
    modelo: "GA 315 VSD COMP AR",
    numeroSerie: "APFS90967404",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "3",
    tag: "CB-2020-26",
    modelo: "ZT 275FF ZT275 8.6FF",
    numeroSerie: "BQD106934",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "Resfriador coletado pela Vale",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "4",
    tag: "SC-2020-02",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081488",
    localizacao: "Filtragem",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "5",
    tag: "SC-2020-02",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081460",
    localizacao: "Filtragem",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "6",
    tag: "SC-2020-03",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081487",
    localizacao: "Filtragem",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "7",
    tag: "SC-2020-03",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081500",
    localizacao: "Filtragem",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "8",
    tag: "SC-2020-06",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081507",
    localizacao: "Filtragem",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "9",
    tag: "SC-2020-06",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081494",
    localizacao: "Filtragem",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "10",
    tag: "CB-2020-04",
    modelo: "GA110-100AP",
    numeroSerie: "BRP075254",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "Aditivo recente",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "11",
    tag: "CB-2020-24",
    modelo: "ZT2758.6FF",
    numeroSerie: "BQD107036",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "12",
    tag: "CB-2020-25",
    modelo: "ZT 275FF ZT275 8.6FF",
    numeroSerie: "BQD107037",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "Programação para execução - Material entregue",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "13",
    tag: "CB-2020SA-31",
    modelo: "GA 110 AP COMP",
    numeroSerie: "BQD119297",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "Aguardando envio dos filtros corretos",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "14",
    tag: "FL-5008-14",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081505",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "15",
    tag: "SC-5008-15",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081508",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "16",
    tag: "FL-5008-16",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081492 (5008-03)",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "17",
    tag: "FL-5008-17",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081506 (5008-02)",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "18",
    tag: "FL-5008-18",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081493 (5008-01)",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "19",
    tag: "FL-5008-19",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081498",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "20",
    tag: "FL-5008-20",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081485",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "21",
    tag: "FL-5008-22",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081499",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "22",
    tag: "SC-5008-04",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081486",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "23",
    tag: "SC-5008-04",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081501",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "24",
    tag: "SC-5008-05",
    modelo: "Filtro - PD525",
    numeroSerie: "NSE081509",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "25",
    tag: "CB-5013-12",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BRP081503",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "26",
    tag: "CB-5008-11",
    modelo: "GA 160 GA160+8.6A",
    numeroSerie: "BRP080378",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "27",
    tag: "SC-5008-02",
    modelo: "FX 18 Secadores e Filtros",
    numeroSerie: "ITJ043302",
    localizacao: "Flotação",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "Programação para execução",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "28",
    tag: "BO-5015SA-02",
    modelo: "ZL 2 VSD Soprador ZL2",
    numeroSerie: "ITJ2889751",
    localizacao: "Britagem",
    tipo: "Soprador",
    temContrato: true,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Em Atraso",
    dataParada: "2024-11-04",
    acao: "VALE",
    observacoes:
      "Solicitado o envio do inversor para nossa oficina em 14/04, logistica da Vale está dando andamento no processo.Preventiva será feita no retorno do inversor",
    responsavel: "VALE",
    tempo: 375,
  },
  {
    id: "29",
    tag: "CB-2020-03",
    modelo: "GA110-100AP",
    numeroSerie: "BRP075253",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Em Atraso",
    dataParada: "2025-03-25",
    acao: "VALE",
    observacoes: "Motor enviado para revisão no fornecedor Kaíros",
    responsavel: "VALE",
    tempo: 234,
  },
  {
    id: "30",
    tag: "CB-5013-03",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BRP072166",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Parada",
    manutencaoPreventiva: "OK",
    dataParada: "2025-02-04",
    acao: "VALE",
    observacoes: "Aguardando envio das peças conclusão de montagem, aguardando aditivo para envio das peças",
    responsavel: "VALE",
    tempo: 283,
  },
  {
    id: "31",
    tag: "CB-1024SA-01",
    modelo: "GA 37+ 175 AP",
    numeroSerie: "BRP071422",
    localizacao: "Mina de Salobo - Posto Pesado",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Parada",
    manutencaoPreventiva: "OK",
    dataParada: "2024-11-01",
    acao: "VALE",
    observacoes: "Atividade sendo realizada pelo time da Britagem, acompanhada pelo Fernando Teixeira. (Vale)",
    responsavel: "VALE",
    tempo: 378,
  },
  {
    id: "32",
    tag: "CB-5008-02",
    modelo: "GA160 100-150",
    numeroSerie: "BRP071324",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: false,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Fora de Contrato",
    dataParada: "2024-07-11",
    acao: "VALE",
    observacoes: "Aguardando aditivo para envio de peças",
    responsavel: "VALE",
    tempo: 491,
  },
  {
    id: "33",
    tag: "SC-5008-01",
    modelo: "FD 310 440V",
    numeroSerie: "BRP071235",
    localizacao: "Flotação",
    tipo: "Secador",
    temContrato: false,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Fora de Contrato",
    dataParada: "2015-06-01",
    acao: "VALE",
    observacoes: "Aguardando aditivo para envio de peças",
    responsavel: "VALE",
    tempo: 3787,
  },
  {
    id: "34",
    tag: "SC-5008-11",
    modelo: "FD 310 440V",
    numeroSerie: "BRP081165",
    localizacao: "Flotação",
    tipo: "Secador",
    temContrato: false,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Fora de Contrato",
    dataParada: "2016-07-04",
    acao: "VALE",
    observacoes: "Aguardando aditivo para envio de peças",
    responsavel: "VALE",
    tempo: 3419,
  },
  {
    id: "35",
    tag: "SC-5008-12",
    modelo: "FD2000",
    numeroSerie: "APF220302",
    localizacao: "Flotação",
    tipo: "Secador",
    temContrato: false,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Fora de Contrato",
    dataParada: "2024-11-06",
    acao: "VALE",
    observacoes: "Aguardando aditivo para envio de peças",
    responsavel: "VALE",
    tempo: 373,
  },
  {
    id: "36",
    tag: "SC-5008-13",
    modelo: "FX",
    numeroSerie: "COMP-SV0079",
    localizacao: "Flotação",
    tipo: "Secador",
    temContrato: false,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Fora de Contrato",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "37",
    tag: "SC-5008-15",
    modelo: "FD2000",
    numeroSerie: "APF220244",
    localizacao: "Flotação",
    tipo: "Secador",
    temContrato: false,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Fora de Contrato",
    dataParada: null,
    acao: "VALE",
    observacoes: "Equipamento com sobrecarga no ventilador",
    responsavel: "VALE",
    tempo: 0,
  },
  {
    id: "38",
    tag: "CB-1024SA-02",
    modelo: "GA 45+ 100 AP",
    numeroSerie: "BRP071423",
    localizacao: "Mina de Salobo - Posto Pesado",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "VALE",
    observacoes: "Aguardando disponibilidade de parada; equipamento apresentando ruído",
    responsavel: "VALE",
    tempo: 0,
  },
  {
    id: "39",
    tag: "CB-5201SA-01",
    modelo: "GX 11",
    numeroSerie: "BQD119293",
    localizacao: "Agua recuperada",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "40",
    tag: "CB-5201SA-02",
    modelo: "GX 11",
    numeroSerie: "BQD119294",
    localizacao: "Agua recuperada",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "41",
    tag: "CB-2104SA-01",
    modelo: "GA55 100 AP COMP AR",
    numeroSerie: "BQD119295",
    localizacao: "Britagem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "42",
    tag: "CB-2104SA-02",
    modelo: "GA55 100 AP COMP AR",
    numeroSerie: "BQD119296",
    localizacao: "Britagem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "43",
    tag: "SC-2104SA-01",
    modelo: "FX15 Secadores e Filtros",
    numeroSerie: "ITJ294894",
    localizacao: "Britagem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "44",
    tag: "SC-2104SA-02",
    modelo: "FX15 Secadores e Filtros",
    numeroSerie: "ITJ294895",
    localizacao: "Britagem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "45",
    tag: "BO-5015SA-01",
    modelo: "ZL 2 VSD Soprador ZL2",
    numeroSerie: "ITJ289551",
    localizacao: "Britagem",
    tipo: "Soprador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "46",
    tag: "CB-2316SA-02",
    modelo: "G160 VSD GA160",
    numeroSerie: "BQD119323",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "47",
    tag: "SC-2020-06",
    modelo: "FX 18 Secadores e Filtros",
    numeroSerie: "CAI921344",
    localizacao: "Filtragem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "48",
    tag: "SC-2020SA-31",
    modelo: "FX 19 Secadores e Filtros",
    numeroSerie: "ITJ290645",
    localizacao: "Filtragem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "49",
    tag: "SC-2020SA-32",
    modelo: "FX 19 Secadores e Filtros",
    numeroSerie: "ITJ290647",
    localizacao: "Filtragem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "50",
    tag: "CB-2020-01",
    modelo: "GA 110 GA110-100AP",
    numeroSerie: "BRP075251",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "51",
    tag: "CB-2020-02",
    modelo: "GA 110 GA110-100AP",
    numeroSerie: "BRP075252",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "52",
    tag: "CB-2020-21",
    modelo: "GA 110 COMP AR",
    numeroSerie: "BQD117168",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "ATLAS",
    observacoes: "Envio do motor do ventilador previsto para 15/09",
    responsavel: "ATLAS",
    tempo: 0,
  },
  {
    id: "53",
    tag: "CB-2020SA-32",
    modelo: "GA 110 AP COMP",
    numeroSerie: "BQD119298",
    localizacao: "Filtragem",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "54",
    tag: "SC-2020-03",
    modelo: "FX 18 Secadores e Filtros",
    numeroSerie: "CAI921343",
    localizacao: "Filtragem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "55",
    tag: "SC-2020-04",
    modelo: "FX 18 Secadores e Filtros",
    numeroSerie: "CAI921342",
    localizacao: "Filtragem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "56",
    tag: "SC-2020-05",
    modelo: "FX 18 Secadores e Filtros",
    numeroSerie: "CAI921345",
    localizacao: "Filtragem",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "57",
    tag: "CB-5008-01",
    modelo: "GA 160 GA160",
    numeroSerie: "BRP071323",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "58",
    tag: "CB-5008-03",
    modelo: "GA 160 GA160",
    numeroSerie: "BRP071325",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "59",
    tag: "CB-5008-12",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BQD109691",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: "2025-08-08",
    acao: "VALE",
    observacoes: "Motor principal com problema no rolamento dianteiro. Será tratado pelo fornecedor Cairos",
    responsavel: "VALE",
    tempo: 0,
  },
  {
    id: "60",
    tag: "CB-5013-01",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BRP071936",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: "VALE",
    observacoes: "Problema na subestação (aguardando elétrica)",
    responsavel: "VALE",
    tempo: 0,
  },
  {
    id: "61",
    tag: "SC-5008-05",
    modelo: "Filtro -DD525",
    numeroSerie: "NSE081495",
    localizacao: "Flotação",
    tipo: "Filtro",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Em Atraso",
    dataParada: null,
    acao: null,
    observacoes: "Art aprovada, em agendamento",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "62",
    tag: "CB-2316SA-08",
    modelo: "GA 315 VSD COMP AR",
    numeroSerie: "APFS90967405",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: false,
    statusOperacional: "Parada",
    manutencaoPreventiva: "Fora de Contrato",
    dataParada: "2024-10-21",
    acao: "VALE",
    observacoes: "Em processo de campras pelo time da elétrica, sendo acompanhado pelo Luiz Almeida",
    responsavel: "VALE",
    tempo: 389,
  },
  {
    id: "63",
    tag: "CB-5013-02",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BRP071937",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "64",
    tag: "CB-5013-04",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BRP071935",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "65",
    tag: "CB-5013-11",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BRP081504",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "66",
    tag: "CB-5013-13",
    modelo: "ZR 630 ZR630-8,6",
    numeroSerie: "BRP081505",
    localizacao: "Flotação",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "67",
    tag: "CB-2316SA-01",
    modelo: "G160 VSD GA160",
    numeroSerie: "BQD119324",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Parada",
    manutencaoPreventiva: "OK",
    dataParada: "2025-08-20",
    acao: "VALE",
    observacoes: "Elemento compressor travado, orçamento enviado ao Anderson Machado em 20/08",
    responsavel: "VALE",
    tempo: 56,
  },
  {
    id: "68",
    tag: "CB-2316SA-03",
    modelo: "G160 VSD GA160",
    numeroSerie: "BQD119325",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "69",
    tag: "CB-2316SA-04",
    modelo: "GA 315 VSD COMP AR",
    numeroSerie: "S90967401",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "70",
    tag: "CB-2316SA-05",
    modelo: "GA 315 VSD COMP AR",
    numeroSerie: "S90967402",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: "VALE",
    observacoes: "Pendente elétrica rearmar subestação",
    responsavel: "VALE",
    tempo: 0,
  },
  {
    id: "71",
    tag: "CB-2316SA-06",
    modelo: "GA 315 VSD COMP AR",
    numeroSerie: "S90967403",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "72",
    tag: "CB-2316SA-09",
    modelo: "GA 315 VSD COMP AR",
    numeroSerie: "S90967406",
    localizacao: "Flotação SL III",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "73",
    tag: "SC-2316SA-01",
    modelo: "FX 19 Secadores e Filtros",
    numeroSerie: "ITJ290643",
    localizacao: "Flotação SL III",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "74",
    tag: "SC-2316SA-02",
    modelo: "FX 19 Secadores e Filtros",
    numeroSerie: "ITJ290644",
    localizacao: "Flotação SL III",
    tipo: "Secador",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "75",
    tag: "CB-6044SA-01",
    modelo: "GA90AP200",
    numeroSerie: "BQR131279",
    localizacao: "Mina de Salobo - Manutenção de Pneus",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "76",
    tag: "CP-1023SA-01",
    modelo: "GA45AP200",
    numeroSerie: "BQR131278",
    localizacao: "Mina de Salobo - Oficina Central",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "OK",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "77",
    tag: "Reservatório SLB3",
    modelo: "DD 5000+",
    numeroSerie: "APF243204",
    localizacao: "Reservatório SLB3",
    tipo: "Reservatório",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Em Atraso",
    dataParada: null,
    acao: null,
    observacoes: "",
    responsavel: "",
    tempo: 0,
  },
  {
    id: "78",
    tag: "CB-1023SA-02",
    modelo: "GA 45+ 100 AP",
    numeroSerie: "BRP071425",
    localizacao: "Mina de Salobo - Oficina Central",
    tipo: "Compressor",
    temContrato: true,
    statusOperacional: "Operacional",
    manutencaoPreventiva: "Andamento",
    dataParada: null,
    acao: null,
    observacoes: "Aguardando elemento compressor Vale",
    responsavel: "",
    tempo: 0,
  },
]

export const historicoSemanalReal = [
  {
    weekNumber: 28,
    weekLabel: "Semana 28 (15/09/2025)",
    date: "2025-09-15",
    totalMachines: 78,
    operational: 68,
    stopped: 10,
    availability: 87.2,
  },
  {
    weekNumber: 29,
    weekLabel: "Semana 29 (29/09/2025)",
    weekDate: "2025-09-29",
    totalMachines: 78,
    operational: 68,
    stopped: 10,
    availability: 87.2,
  },
  {
    weekNumber: 40,
    weekLabel: "Semana 40 (06/10/2025)",
    date: "2025-10-06",
    totalMachines: 78,
    operational: 68,
    stopped: 10,
    availability: 87.2,
  },
  {
    weekNumber: 41,
    weekLabel: "Semana 41 (13/10/2025)",
    date: "2025-10-13",
    totalMachines: 78,
    operational: 68,
    stopped: 10,
    availability: 87.2,
  },
]

export function criarRegistrosSemanaisReais() {
  const semanas = [
    { data: "2025-09-15", semana: "2025-W38", label: "Semana 38 (15/09/2025)" },
    { data: "2025-09-29", semana: "2025-W40", label: "Semana 40 (29/09/2025)" },
    { data: "2025-10-06", semana: "2025-W41", label: "Semana 41 (06/10/2025)" },
    { data: "2025-10-13", semana: "2025-W42", label: "Semana 42 (13/10/2025)" },
  ]

  return semanas.map((semana, index) => ({
    id: `registro-real-${index + 1}`,
    semana: semana.semana,
    dataRegistro: semana.data,
    maquinas: dadosReaisMaquinas.map((m) => ({
      id: m.id,
      nome: m.tag,
      tipo: m.tipo,
      numeroSerie: m.numeroSerie,
      data: semana.data,
      dataParada: m.dataParada,
      status: (m.statusOperacional === "Operacional"
        ? "operacional"
        : m.statusOperacional === "Parada"
          ? "parada"
          : "manutencao") as "operacional" | "parada" | "manutencao",
      motivoParada: m.observacoes || undefined,
      manutencaoPreventiva: m.manutencaoPreventiva,
      localizacao: m.localizacao,
      acaoResponsavel: m.acao || undefined,
      statusPreventiva: m.manutencaoPreventiva,
      descricaoDetalhada: m.observacoes,
      temContrato: m.temContrato,
      responsavel: m.responsavel,
      tempoParada: m.tempo,
    })),
  }))
}

export function loadRealData() {
  const machines = dadosReaisMaquinas.map((m) => {
    let acaoResponsavel: "Vale" | "Atlas" | undefined = undefined
    if (m.acao === "VALE") {
      acaoResponsavel = "Vale"
    } else if (m.acao === "ATLAS") {
      acaoResponsavel = "Atlas"
    }

    return {
      id: m.id,
      nome: m.tag,
      tipo: m.tipo,
      modelo: m.modelo,
      numeroSerie: m.numeroSerie,
      localizacao: m.localizacao,
      data: new Date().toISOString().split("T")[0],
      status: (m.statusOperacional === "Operacional"
        ? "operacional"
        : m.statusOperacional === "Parada"
          ? "parada"
          : "manutencao") as "operacional" | "parada" | "manutencao",
      motivoParada: m.observacoes || "",
      descricaoDetalhada: m.observacoes || "",
      acaoResponsavel,
      dataParada: m.dataParada || undefined,
      statusPreventiva: (m.manutencaoPreventiva === "OK"
        ? "OK"
        : m.manutencaoPreventiva === "Em Atraso"
          ? "Em Atraso"
          : "Em Planejamento") as "OK" | "Em Atraso" | "Em Planejamento",
      dataPreventiva: undefined,
      manutencaoPreventiva: m.manutencaoPreventiva,
      temContrato: m.temContrato,
      responsavel: m.responsavel,
      tempoParada: m.tempo,
    }
  })

  const history = historicoSemanalReal.map((h) => ({
    id: `snapshot-${h.weekNumber}`,
    semana: `2025-W${h.weekNumber}`,
    data: h.date,
    totalMachines: h.totalMachines,
    operational: h.operational,
    stopped: h.stopped,
    maintenance: 0,
    availability: h.availability,
  }))

  return { machines, history }
}
