import type { WeeklySnapshot } from "./types"

export const historicalSnapshots: WeeklySnapshot[] = [
  {
    id: "snapshot-2025-W23",
    weekId: "2025-W23",
    date: "2025-06-05",
    machines: [
      // Máquinas paradas em todas as semanas
      {
        id: "1",
        nome: "SC-2020-02",
        tipo: "Secador",
        modelo: "FX 18 Secadores e Filtros",
        numeroSerie: "CAI921341",
        localizacao: "Filtragem",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Equipamento com vazamento de gás",
        descricaoDetalhada: "Equipamento com vazamento de gás",
        acaoResponsavel: "Atlas",
        dataParada: "2025-09-26",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "OK",
        temContrato: true,
        responsavel: "ATLAS",
        tempoParada: 109,
      },
      {
        id: "2",
        nome: "BO-5015SA-02",
        tipo: "Soprador",
        modelo: "ZL 2 VSD Soprador ZL2",
        numeroSerie: "ITJ2889751",
        localizacao: "Britagem",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Solicitado o envio do inversor para nossa oficina",
        descricaoDetalhada: "Solicitado o envio do inversor para nossa oficina em 14/04",
        acaoResponsavel: "Vale",
        dataParada: "2024-11-04",
        statusPreventiva: "Em Atraso",
        dataPreventiva: undefined,
        manutencaoPreventiva: "Em Atraso",
        temContrato: true,
        responsavel: "VALE",
        tempoParada: 375,
      },
      {
        id: "3",
        nome: "CB-2020-03",
        tipo: "Compressor",
        modelo: "GA110-100AP",
        numeroSerie: "BRP075253",
        localizacao: "Filtragem",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Motor enviado para revisão no fornecedor Kaíros",
        descricaoDetalhada: "Motor enviado para revisão no fornecedor Kaíros",
        acaoResponsavel: "Vale",
        dataParada: "2025-03-25",
        statusPreventiva: "Em Atraso",
        dataPreventiva: undefined,
        manutencaoPreventiva: "Em Atraso",
        temContrato: true,
        responsavel: "VALE",
        tempoParada: 234,
      },
      {
        id: "4",
        nome: "CB-5013-03",
        tipo: "Compressor",
        modelo: "ZR 630 ZR630-8,6",
        numeroSerie: "BRP072166",
        localizacao: "Flotação",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Aguardando envio das peças conclusão de montagem",
        descricaoDetalhada: "Aguardando envio das peças conclusão de montagem, aguardando aditivo para envio das peças",
        acaoResponsavel: "Vale",
        dataParada: "2025-02-04",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "OK",
        temContrato: true,
        responsavel: "VALE",
        tempoParada: 283,
      },
      {
        id: "5",
        nome: "CB-1024SA-01",
        tipo: "Compressor",
        modelo: "GA 37+ 175 AP",
        numeroSerie: "BRP071422",
        localizacao: "Mina de Salobo - Posto Pesado",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Atividade sendo realizada pelo time da Britagem",
        descricaoDetalhada:
          "Atividade sendo realizada pelo time da Britagem, acompanhada pelo Fernando Teixeira. (Vale)",
        acaoResponsavel: "Vale",
        dataParada: "2024-11-01",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "OK",
        temContrato: true,
        responsavel: "VALE",
        tempoParada: 378,
      },
      {
        id: "6",
        nome: "CB-5008-02",
        tipo: "Compressor",
        modelo: "GA160 100-150",
        numeroSerie: "BRP071324",
        localizacao: "Flotação",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Aguardando aditivo para envio de peças",
        descricaoDetalhada: "Aguardando aditivo para envio de peças",
        acaoResponsavel: "Vale",
        dataParada: "2024-07-11",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "Fora de Contrato",
        temContrato: false,
        responsavel: "VALE",
        tempoParada: 491,
      },
      {
        id: "7",
        nome: "SC-5008-01",
        tipo: "Secador",
        modelo: "FD 310 440V",
        numeroSerie: "BRP071235",
        localizacao: "Flotação",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Aguardando aditivo para envio de peças",
        descricaoDetalhada: "Aguardando aditivo para envio de peças",
        acaoResponsavel: "Vale",
        dataParada: "2015-06-01",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "Fora de Contrato",
        temContrato: false,
        responsavel: "VALE",
        tempoParada: 3787,
      },
      {
        id: "8",
        nome: "SC-5008-11",
        tipo: "Secador",
        modelo: "FD 310 440V",
        numeroSerie: "BRP081165",
        localizacao: "Flotação",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Aguardando aditivo para envio de peças",
        descricaoDetalhada: "Aguardando aditivo para envio de peças",
        acaoResponsavel: "Vale",
        dataParada: "2016-07-04",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "Fora de Contrato",
        temContrato: false,
        responsavel: "VALE",
        tempoParada: 3419,
      },
      {
        id: "9",
        nome: "SC-5008-12",
        tipo: "Secador",
        modelo: "FD2000",
        numeroSerie: "APF220302",
        localizacao: "Flotação",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Aguardando aditivo para envio de peças",
        descricaoDetalhada: "Aguardando aditivo para envio de peças",
        acaoResponsavel: "Vale",
        dataParada: "2024-11-06",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "Fora de Contrato",
        temContrato: false,
        responsavel: "VALE",
        tempoParada: 373,
      },
      {
        id: "10",
        nome: "CB-2316SA-08",
        tipo: "Compressor",
        modelo: "GA 315 VSD COMP AR",
        numeroSerie: "APFS90967405",
        localizacao: "Flotação SL III",
        data: "2025-06-05",
        status: "parada",
        motivoParada: "Em processo de compras pelo time da elétrica",
        descricaoDetalhada: "Em processo de compras pelo time da elétrica, sendo acompanhado pelo Luiz Almeida",
        acaoResponsavel: "Vale",
        dataParada: "2024-10-21",
        statusPreventiva: "OK",
        dataPreventiva: undefined,
        manutencaoPreventiva: "Fora de Contrato",
        temContrato: false,
        responsavel: "VALE",
        tempoParada: 389,
      },
      // Máquinas operacionais (restante das 78 máquinas)
      // ... (código continua com todas as outras máquinas operacionais)
    ],
  },
  // ... (outros snapshots para as outras semanas)
]
